import AsyncStorage from "@react-native-async-storage/async-storage";
import { useRouter } from "expo-router";
import React, { useEffect, useState } from "react";
import { Pressable, StyleSheet, Text, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { Icon, styles as ui } from "@/components/mintune-ui";
import { COLORS, EQUALIZER_BANDS, EQUALIZER_PRESETS } from "@/lib/mintune-data";

const CURVES: Record<string, number[]> = { 平衡: [0, 0, 0, 0, 0], 流行: [3, 2, -1, 2, 3], 古典: [2, 1, 0, 2, 3], 人声: [-1, 1, 3, 2, -1], 低音: [4, 3, 1, -1, -2] };
const STORAGE_KEY = "mintune:equalizer";
export default function EqualizerScreen() {
  const router = useRouter(); const [preset, setPreset] = useState(EQUALIZER_PRESETS[0]); const [levels, setLevels] = useState(CURVES[EQUALIZER_PRESETS[0]]);
  useEffect(() => { AsyncStorage.getItem(STORAGE_KEY).then((value) => { if (!value) return; try { const saved = JSON.parse(value) as { preset?: string; levels?: number[] }; if (saved.preset && CURVES[saved.preset]) setPreset(saved.preset); if (saved.levels?.length === EQUALIZER_BANDS.length) setLevels(saved.levels); } catch { /* reset to defaults */ } }); }, []);
  const save = (nextPreset: string, nextLevels: number[]) => { setPreset(nextPreset); setLevels(nextLevels); void AsyncStorage.setItem(STORAGE_KEY, JSON.stringify({ preset: nextPreset, levels: nextLevels })); };
  const updateLevel = (index: number) => { const next = levels.map((value, itemIndex) => itemIndex === index ? value >= 4 ? -4 : value + 1 : value); save("自定义", next); };
  return <ScreenContainer edges={["top", "bottom", "left", "right"]} containerClassName="bg-background"><View style={styles.content}>
    <View style={styles.topBar}><Pressable accessibilityLabel="返回设置" onPress={() => router.back()} style={({ pressed }) => [styles.topButton, pressed && ui.pressed]}><Icon name="arrow-back" size={22} color={COLORS.text} /></Pressable><Text style={styles.topTitle}>均衡器</Text><Pressable accessibilityLabel="关闭均衡器" onPress={() => router.dismiss()} style={({ pressed }) => [styles.topButton, pressed && ui.pressed]}><Icon name="close" size={22} color={COLORS.text} /></Pressable></View>
    <View style={styles.intro}><View style={styles.introIcon}><Icon name="equalizer" size={25} color={COLORS.background} /></View><Text style={styles.introTitle}>塑造你的声音</Text><Text style={styles.introText}>预设曲线和个人调整会保存在本机。</Text></View>
    <Text style={styles.sectionLabel}>预设</Text><View style={styles.presetRow}>{EQUALIZER_PRESETS.map((item) => <Pressable key={item} onPress={() => save(item, CURVES[item])} style={({ pressed }) => [styles.presetPill, preset === item && styles.presetActive, pressed && ui.pressed]}><Text style={[styles.presetText, preset === item && styles.presetTextActive]}>{item}</Text></Pressable>)}</View>
    <View style={styles.eqCard}><View style={styles.bars}>{levels.map((level, index) => <Pressable key={EQUALIZER_BANDS[index]} onPress={() => updateLevel(index)} style={({ pressed }) => [styles.band, pressed && ui.pressed]}><View style={styles.track}><View style={[styles.level, { height: `${Math.max(17, ((level + 4) / 8) * 100)}%` }]} /></View><Text style={styles.bandLabel}>{EQUALIZER_BANDS[index]}</Text><Text style={styles.bandValue}>{level > 0 ? `+${level}` : level} dB</Text></Pressable>)}</View></View>
    <View style={styles.infoCard}><Icon name="headphones" size={19} color={COLORS.mint} /><View style={styles.infoCopy}><Text style={styles.infoTitle}>本地预设</Text><Text style={styles.infoText}>当前版本保存 EQ 曲线；系统级 DSP 将在原生音频模块接入后生效。</Text></View></View>
  </View></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { flex: 1, paddingHorizontal: 20, paddingTop: 8 }, topBar: { height: 42, flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, topButton: { width: 38, height: 38, borderRadius: 19, alignItems: "center", justifyContent: "center", backgroundColor: COLORS.surface }, topTitle: { color: COLORS.text, fontSize: 14, fontWeight: "800" }, intro: { alignItems: "center", marginTop: 35, marginBottom: 35 }, introIcon: { width: 58, height: 58, borderRadius: 20, alignItems: "center", justifyContent: "center", backgroundColor: COLORS.mint, marginBottom: 15 }, introTitle: { color: COLORS.text, fontSize: 24, fontWeight: "800" }, introText: { color: COLORS.muted, fontSize: 12, marginTop: 7 }, sectionLabel: { color: COLORS.muted, fontSize: 11, fontWeight: "800", letterSpacing: 1, marginBottom: 10 }, presetRow: { flexDirection: "row", flexWrap: "wrap", gap: 8 }, presetPill: { paddingHorizontal: 14, paddingVertical: 9, borderRadius: 999, backgroundColor: COLORS.surface, borderWidth: 1, borderColor: COLORS.divider }, presetActive: { backgroundColor: COLORS.mint, borderColor: COLORS.mint }, presetText: { color: COLORS.muted, fontSize: 12, fontWeight: "700" }, presetTextActive: { color: COLORS.background }, eqCard: { marginTop: 26, padding: 18, borderRadius: 22, backgroundColor: COLORS.surface, borderWidth: 1, borderColor: COLORS.divider }, bars: { height: 245, flexDirection: "row", justifyContent: "space-around", gap: 12 }, band: { flex: 1, alignItems: "center", justifyContent: "flex-end" }, track: { width: 8, flex: 1, justifyContent: "flex-end", borderRadius: 6, backgroundColor: COLORS.divider, overflow: "hidden" }, level: { width: "100%", borderRadius: 6, backgroundColor: COLORS.mint }, bandLabel: { color: COLORS.muted, fontSize: 10, marginTop: 11 }, bandValue: { color: COLORS.subtle, fontSize: 9, marginTop: 4 }, infoCard: { flexDirection: "row", alignItems: "center", gap: 11, padding: 15, marginTop: 16, borderRadius: 17, backgroundColor: "rgba(94,234,212,0.08)" }, infoCopy: { flex: 1 }, infoTitle: { color: COLORS.mint, fontSize: 12, fontWeight: "800" }, infoText: { color: COLORS.muted, fontSize: 11, lineHeight: 16, marginTop: 4 } });
