import { useRouter } from "expo-router";
import Constants from "expo-constants";
import * as DocumentPicker from "expo-document-picker";
import * as FileSystem from "expo-file-system/legacy";
import * as Sharing from "expo-sharing";
import React, { useState } from "react";
import { Image, Pressable, ScrollView, StyleSheet, Switch, Text, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { AppDialog, Icon, PageHeader, ScanProgressModal, styles as ui } from "@/components/mintune-ui";
import { APP_VERSION, COLORS, PLAYBACK_SPEEDS, SUPPORTED_FORMATS } from "@/lib/mintune-data";
import { usePlayer } from "@/lib/player-context";
import { useThemeContext } from "@/lib/theme-provider";
import { exportDatabaseBackup, importDatabaseBackup } from "@/lib/database";
import { exportDiagnostics, logError, logEvent } from "@/lib/diagnostics";

export default function SettingsScreen() {
  const router = useRouter(); const player = usePlayer(); const { colorScheme, setColorScheme } = useThemeContext();
  const [quality, setQuality] = useState("自动"); const [scanning, setScanning] = useState(false); const [scanVisible, setScanVisible] = useState(false); const [scanProgress, setScanProgress] = useState({ current: 0, total: 0, filename: "", recent: [] as string[] }); const [dialog, setDialog] = useState<{ title: string; message: string } | null>(null);
  const darkMode = colorScheme === "dark"; const appVersion = Constants.nativeAppVersion ?? Constants.expoConfig?.version ?? APP_VERSION;
  const openMessage = (title: string, message: string) => setDialog({ title, message });
  const scanMusic = async () => { if (scanning) return; setScanning(true); setScanVisible(true); setScanProgress({ current: 0, total: 0, filename: "准备扫描…", recent: [] }); try { const count = await player.scanLocalMusic((progress) => setScanProgress((state) => ({ current: progress.current, total: progress.total, filename: progress.filename, recent: progress.track ? [...state.recent, progress.track.title] : state.recent }))); setScanProgress((state) => ({ ...state, current: count, total: Math.max(count, state.total), filename: `扫描完成，共 ${count} 首歌曲` })); } catch (error) { setScanVisible(false); openMessage("无法扫描音乐", error instanceof Error ? error.message : "请检查音乐访问权限后重试。"); } finally { setScanning(false); } };
  const nextSpeed = PLAYBACK_SPEEDS[(PLAYBACK_SPEEDS.indexOf(player.playbackSpeed) + 1) % PLAYBACK_SPEEDS.length];
  const sleepLabel = player.sleepRemaining == null ? "关闭" : `${player.sleepRemaining} 分钟后停止`;
  const backupData = async () => { try { const path = `${FileSystem.cacheDirectory}mintune-backup-${new Date().toISOString().slice(0, 10)}.json`; await FileSystem.writeAsStringAsync(path, exportDatabaseBackup()); if (await Sharing.isAvailableAsync()) await Sharing.shareAsync(path, { mimeType: "application/json", dialogTitle: "导出 Mintune 备份" }); else openMessage("备份已生成", path); } catch (error) { openMessage("导出失败", error instanceof Error ? error.message : "无法生成备份文件。\n请稍后重试。"); } };
  const restoreData = async () => { try { const result = await DocumentPicker.getDocumentAsync({ type: "application/json", copyToCacheDirectory: true }); if (result.canceled) return; const content = await FileSystem.readAsStringAsync(result.assets[0].uri); const count = importDatabaseBackup(content); player.refreshDatabase(); openMessage("恢复完成", `已恢复 ${count} 首歌曲及本地歌单、收藏和播放历史。`); } catch (error) { openMessage("恢复失败", error instanceof Error ? error.message : "备份文件无效或无法读取。\n原有数据未被修改。"); } };
  const exportLogs = async () => { try { logEvent("export_diagnostics"); const path = await exportDiagnostics(); if (await Sharing.isAvailableAsync()) await Sharing.shareAsync(path, { mimeType: "application/json", dialogTitle: "导出 Mintune 诊断日志" }); else openMessage("诊断日志已生成", path); } catch (error) { logError(error, { source: "export_diagnostics" }); openMessage("导出失败", "无法生成诊断日志，请稍后重试。"); } };
  return <ScreenContainer edges={["top", "left", "right"]} containerClassName="bg-background"><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
    <PageHeader eyebrow="YOUR SPACE" title="设置" subtitle="让播放体验更贴近你" />
    <View style={styles.brandCard}><Image source={require("@/assets/images/mintune-logo.png")} style={styles.brandLogo} resizeMode="contain" accessibilityLabel="Mintune 薄荷音乐 Logo" /></View>
    <View style={styles.profileCard}><View style={styles.avatar}><Text style={styles.avatarText}>M</Text></View><View style={styles.profileCopy}><Text style={styles.profileTitle}>本地音乐空间</Text><Text style={styles.profileSubtitle}>无需注册账号，数据只保存在本机</Text></View><Icon name="offline-pin" size={20} color={COLORS.mint} /></View>
    <SettingGroup title="外观"><SettingRow icon="dark-mode" title="深色模式" subtitle={darkMode ? "已开启深色主题" : "已跟随浅色主题"} right={<Switch value={darkMode} onValueChange={(value) => setColorScheme(value ? "dark" : "light")} trackColor={{ false: COLORS.divider, true: COLORS.mint }} thumbColor={darkMode ? COLORS.background : COLORS.muted} />} /><SettingRow icon="language" title="语言" subtitle="简体中文" onPress={() => openMessage("语言", "当前版本支持简体中文。" )} /></SettingGroup>
    <SettingGroup title="播放与音质"><SettingRow icon="equalizer" title="均衡器" subtitle="预设曲线可调整并保存在本地" onPress={() => router.push("/equalizer" as never)} /><SettingRow icon="graphic-eq" title="播放音质" subtitle={quality === "自动" ? "自动 · 根据文件格式播放" : quality} onPress={() => setQuality(quality === "自动" ? "高解析" : "自动")} /><SettingRow icon="speed" title="播放速度" subtitle={`${player.playbackSpeed}×`} onPress={() => player.setPlaybackSpeed(nextSpeed)} /><SettingRow icon="repeat" title="循环模式" subtitle={player.repeatMode === "off" ? "关闭" : player.repeatMode === "all" ? "列表循环" : "单曲循环"} onPress={player.cycleRepeatMode} /><SettingRow icon="shuffle" title="随机播放" subtitle={player.shuffle ? "已开启" : "已关闭"} onPress={player.toggleShuffle} /><SettingRow icon="timer" title="睡眠定时" subtitle={sleepLabel} onPress={() => { const next = player.sleepRemaining == null ? 15 : player.sleepRemaining === 15 ? 30 : player.sleepRemaining === 30 ? 60 : null; player.setSleepTimer(next); }} /><SettingRow icon="sync" title="歌曲衔接" subtitle="由系统音频会话管理中断和耳机断开" /></SettingGroup>
    <SettingGroup title="本地音乐"><SettingRow icon="folder" title={scanning ? `正在扫描… ${scanProgress.current}/${scanProgress.total || "…"}` : "扫描本地音乐"} subtitle="分页读取设备音频并读取元数据、封面和歌词" onPress={scanMusic} /><SettingRow icon="storage" title="存储空间" subtitle={`本地数据库 · ${player.tracks.length} 首歌曲`} onPress={() => openMessage("存储空间", `支持的格式：${SUPPORTED_FORMATS.join("、")}`)} /><SettingRow icon="lock-outline" title="隐私优先" subtitle="不会上传你的音乐文件" onPress={() => openMessage("隐私优先", "不会上传你的音乐文件。音乐资料只保存在这台设备上。")} /></SettingGroup>
    <SettingGroup title="数据安全"><SettingRow icon="file-download" title="导出本地备份" subtitle="保存歌曲元数据、歌单、收藏和播放历史" onPress={backupData} /><SettingRow icon="file-upload" title="恢复本地备份" subtitle="从 JSON 备份文件恢复，不上传到服务器" onPress={restoreData} /></SettingGroup>
    <SettingGroup title="诊断与支持"><SettingRow icon="bug-report" title="导出诊断日志" subtitle="发生闪退或无声时导出，日志只保存在本机" onPress={exportLogs} /></SettingGroup><SettingGroup title="关于 Mintune"><SettingRow icon="info-outline" title="关于 Mintune" subtitle={`版本 ${appVersion} · softly in tune`} onPress={() => openMessage("Mintune", `版本 ${appVersion}\nsoftly in tune`)} /><SettingRow icon="feedback" title="反馈建议" subtitle="欢迎通过 GitHub 项目提交建议" onPress={() => openMessage("反馈建议", "感谢你的反馈！请通过 GitHub 仓库提交建议。")}/></SettingGroup>
    <Text style={styles.footer}>Mintune · softly in tune · 2026</Text>
  </ScrollView><ScanProgressModal visible={scanVisible} current={scanProgress.current} total={scanProgress.total} filename={scanProgress.filename} recent={scanProgress.recent} onClose={() => setScanVisible(false)} /><AppDialog visible={Boolean(dialog)} title={dialog?.title ?? ""} message={dialog?.message ?? ""} onClose={() => setDialog(null)} /></ScreenContainer>;
}
function SettingGroup({ title, children }: { title: string; children: React.ReactNode }) { return <View style={styles.group}><Text style={styles.groupTitle}>{title}</Text><View style={styles.groupCard}>{children}</View></View>; }
function SettingRow({ icon, title, subtitle, right, onPress }: { icon: React.ComponentProps<typeof Icon>["name"]; title: string; subtitle: string; right?: React.ReactNode; onPress?: () => void }) { return <Pressable disabled={!onPress} onPress={onPress} style={({ pressed }) => [styles.row, pressed && ui.pressed]}><View style={styles.rowIcon}><Icon name={icon} size={19} color={COLORS.mint} /></View><View style={styles.rowCopy}><Text style={styles.rowTitle}>{title}</Text><Text numberOfLines={2} style={styles.rowSubtitle}>{subtitle}</Text></View>{right ?? <Icon name="chevron-right" size={19} color={COLORS.subtle} />}</Pressable>; }
const styles = StyleSheet.create({ content: { paddingHorizontal: 20, paddingTop: 14, paddingBottom: 30 }, brandCard: { alignItems: "center", marginBottom: 18, borderRadius: 20, backgroundColor: COLORS.background, overflow: "hidden" }, brandLogo: { width: "100%", height: 110 }, profileCard: { flexDirection: "row", alignItems: "center", padding: 16, marginBottom: 25, borderRadius: 20, backgroundColor: COLORS.surfaceAlt, borderWidth: 1, borderColor: COLORS.divider }, avatar: { width: 49, height: 49, borderRadius: 17, backgroundColor: COLORS.mint, alignItems: "center", justifyContent: "center" }, avatarText: { color: COLORS.background, fontSize: 22, fontWeight: "900" }, profileCopy: { flex: 1, marginLeft: 12 }, profileTitle: { color: COLORS.text, fontSize: 15, fontWeight: "800" }, profileSubtitle: { color: COLORS.muted, fontSize: 11, marginTop: 4 }, group: { marginBottom: 22 }, groupTitle: { color: COLORS.muted, fontSize: 11, fontWeight: "800", letterSpacing: 1.1, marginBottom: 9, textTransform: "uppercase" }, groupCard: { overflow: "hidden", borderRadius: 18, backgroundColor: COLORS.surface, borderWidth: 1, borderColor: COLORS.divider }, row: { minHeight: 68, flexDirection: "row", alignItems: "center", gap: 11, paddingHorizontal: 13, paddingVertical: 10, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: COLORS.divider }, rowIcon: { width: 34, height: 34, borderRadius: 12, alignItems: "center", justifyContent: "center", backgroundColor: "rgba(94,234,212,0.09)" }, rowCopy: { flex: 1 }, rowTitle: { color: COLORS.text, fontSize: 13, fontWeight: "700" }, rowSubtitle: { color: COLORS.muted, fontSize: 10, lineHeight: 15, marginTop: 3 }, footer: { color: COLORS.subtle, fontSize: 10, textAlign: "center", marginTop: 2, marginBottom: 15 } });
